ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;

-- Xoa bang
DROP TABLE C##ADMIN.KHMO;
DROP TABLE C##ADMIN.PHANCONG;
DROP TABLE C##ADMIN.DANGKY;
DROP TABLE C##ADMIN.SINHVIEN;
DROP TABLE C##ADMIN.HOCPHAN;
ALTER TABLE C##ADMIN.NHANSU 
DROP CONSTRAINT FK_NHANSU_DONVI;
DROP TABLE C##ADMIN.DONVI;
DROP TABLE C##ADMIN.NHANSU; 

-- Tao bang 
CREATE TABLE C##ADMIN.NHANSU (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(5),
    NGSINH DATE,
    PHUCAP NUMBER(10),
    DT VARCHAR2(10),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(10)
);

CREATE TABLE C##ADMIN.SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(5),
    NGSINH DATE,
    DCHI VARCHAR2(50),
    DT VARCHAR2(10),
    MACT VARCHAR2(10),
    MANGANH VARCHAR2(10),
    SOTCTL NUMBER,
    DTBTL FLOAT
);

CREATE TABLE C##ADMIN.DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(50),
    TRGDV VARCHAR2(10),
    CONSTRAINT FK_DONVI_NHANSU FOREIGN KEY (TRGDV) REFERENCES NHANSU(MANV)
);

CREATE TABLE C##ADMIN.HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(50),
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    SOSVTD NUMBER,
    MADV VARCHAR2(10),
    CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

CREATE TABLE C##ADMIN.KHMO (
    MAHP VARCHAR2(10),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR2(4),
    CONSTRAINT PK_KHMO PRIMARY KEY (MAHP, HK, NAM, MACT),
    CONSTRAINT CHK_KH_MACT CHECK (MACT IN ('CLC', 'VP', 'CTTT', 'CQ')),
    CONSTRAINT CHK_KH_HK CHECK (HK IN (1, 2, 3)),
    CONSTRAINT FK_KHMO_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);

CREATE TABLE C##ADMIN.PHANCONG (
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR2(4),
    CONSTRAINT FK_PHANCONG_NHANSU FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV),
    CONSTRAINT FK_PHANCONG_KHMO FOREIGN KEY (MAHP, HK, NAM, MACT) REFERENCES KHMO (MAHP, HK, NAM, MACT),
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MAGV, MAHP, HK, NAM, MACT)
);

CREATE TABLE C##ADMIN.DANGKY (
    MASV VARCHAR2(10),
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR2(4),
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_PHANCONG FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT) REFERENCES PHANCONG (MAGV, MAHP, HK, NAM, MACT),
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV, MAGV, MAHP, HK, NAM, MACT)
);

-- Them khoá ngoai
ALTER TABLE NHANSU
ADD CONSTRAINT FK_NHANSU_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

-- Them du lieu cho cac bang
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('VPK', 'Van phong khoa', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('HTTT', 'Bo mon HTTT', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('CNPM', 'Bo mon CNPM', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('KHMT', 'Bo mon KHMT', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('CNTT', 'Bo mon CNTT', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('TGMT', 'Bo mon TGMT', NULL);
INSERT INTO C##ADMIN.DONVI (MADV, TENDV, TRGDV) VALUES ('MMTVT', 'Bo mon MMT và Vien thong', NULL);

INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI001', 'Nguyen Van A', 'Nam', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 500000, '12345678', 'Nhan vien co ban', 'VPK');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI002', 'Tran Thi B', 'Nu', TO_DATE('1995-08-20', 'YYYY-MM-DD'), 5500000, '23456789', 'Nhan vien co ban', 'HTTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI003', 'Le Van C', 'Nam', TO_DATE('1988-02-10', 'YYYY-MM-DD'), 6000000, '34567890', 'Nhan vien co ban', 'CNPM');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI004', 'Pham Thi D', 'Nu', TO_DATE('1992-12-05', 'YYYY-MM-DD'), 5200000, '45678901', 'Nhan vien co ban', 'KHMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI005', 'Hoàng Van E', 'Nam', TO_DATE('1987-10-25', 'YYYY-MM-DD'), 5800000, '56789012', 'Nhan vien co ban', 'CNTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI006', 'Cao Van T', 'Nam', TO_DATE('1987-10-25', 'YYYY-MM-DD'), 5800000, '56789012', 'Nhan vien co ban', 'TGMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('NVI007', 'Pham Van Q', 'Nam', TO_DATE('1987-10-25', 'YYYY-MM-DD'), 5800000, '56789012', 'Nhan vien co ban', 'MMTVT');

INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI001', 'Nguyen Thi F', 'Nu', TO_DATE('1993-07-18', 'YYYY-MM-DD'), 5300000, '67890123', 'Giang vien', 'HTTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI002', 'Tran Van G', 'Nam', TO_DATE('1985-03-30', 'YYYY-MM-DD'), 6200000, '78901234', 'Giang vien', 'HTTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI003', 'Le Thi H', 'Nu', TO_DATE('1990-09-12', 'YYYY-MM-DD'), 5400000, '89012345', 'Giang vien', 'CNPM');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI004', 'Pham Van I', 'Nam', TO_DATE('1989-06-22', 'YYYY-MM-DD'), 5900000, '90123456', 'Giang vien', 'CNPM');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI005', 'Hoàng Thi K', 'Nu', TO_DATE('1994-11-08', 'YYYY-MM-DD'), 5100000, '01234567', 'Giang vien', 'KHMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI006', 'Hoàng Thi F', 'Nu', TO_DATE('1993-07-18', 'YYYY-MM-DD'), 5300000, '67890123', 'Giang vien', 'KHMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI007', 'Pham Van G', 'Nam', TO_DATE('1985-03-30', 'YYYY-MM-DD'), 6200000, '78901234', 'Giang vien', 'CNTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI008', 'Tran Thi H', 'Nu', TO_DATE('1990-09-12', 'YYYY-MM-DD'), 5400000, '89012345', 'Giang vien', 'CNTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI009', 'Hoàng Van I', 'Nam', TO_DATE('1989-06-22', 'YYYY-MM-DD'), 5900000, '90123456', 'Giang vien', 'TGMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI010', 'Le Thi K', 'Nu', TO_DATE('1994-11-08', 'YYYY-MM-DD'), 5100000, '01234567', 'Giang vien', 'TGMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI011', 'Mac Van I', 'Nam', TO_DATE('1989-06-22', 'YYYY-MM-DD'), 5900000, '90123456', 'Giang vien', 'MMTVT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVI012', 'Pham Van L', 'Nam', TO_DATE('1994-11-08', 'YYYY-MM-DD'), 5100000, '01234567', 'Giang vien', 'MMTVT');

INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU001', 'Nguyen Van L', 'Nam', TO_DATE('1986-04-02', 'YYYY-MM-DD'), 6100000, '12345098', 'Giao vu', 'HTTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU002', 'Tran Thi M', 'Nu', TO_DATE('1991-01-28', 'YYYY-MM-DD'), 5500000, '23456098', 'Giao vu', 'CNPM');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU003', 'Le Van N', 'Nam', TO_DATE('1988-08-15', 'YYYY-MM-DD'), 6300000, '34560987', 'Giao vu', 'KHMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU004', 'Pham Thi P', 'Nu', TO_DATE('1993-05-09', 'YYYY-MM-DD'), 5200000, '45609876', 'Giao vu', 'CNTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU005', 'Hoàng Van Q', 'Nam', TO_DATE('1987-12-20', 'YYYY-MM-DD'), 6000000, '56798765', 'Giao vu', 'TGMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('GVU006', 'Nguyen Minh Q', 'Nam', TO_DATE('1987-12-20', 'YYYY-MM-DD'), 6000000, '56798765', 'Giao vu', 'MMTVT');

INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV001', 'Nguyen Thi R', 'Nu', TO_DATE('1992-10-03', 'YYYY-MM-DD'), 5400000, '67897654', 'Truong don vi', 'MMTVT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV002', 'Tran Van S', 'Nam', TO_DATE('1985-06-25', 'YYYY-MM-DD'), 6400000, '78976543', 'Truong don vi', 'HTTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV003', 'Le Thi T', 'Nu', TO_DATE('1990-03-11', 'YYYY-MM-DD'), 5300000, '89065432', 'Truong don vi', 'CNPM');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV004', 'Pham Van U', 'Nam', TO_DATE('1989-09-04', 'YYYY-MM-DD'), 6100000, '90154321', 'Truong don vi', 'KHMT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV005', 'Hoàng Thi V', 'Nu', TO_DATE('1994-02-18', 'YYYY-MM-DD'), 5500000, '01243210', 'Truong don vi', 'CNTT');
INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TDV006', 'Hoàng Minh V', 'Nam', TO_DATE('1994-02-18', 'YYYY-MM-DD'), 5500000, '01243210', 'Truong don vi', 'TGMT');

INSERT INTO C##ADMIN.NHANSU (MANV, HOTEN, PHAI, NGSINH, PHUCAP, DT, VAITRO, MADV) VALUES ('TKH001', 'Nguyen Van X', 'Nam', TO_DATE('1986-07-05', 'YYYY-MM-DD'), 6200000, '12332104', 'Truong khoa', 'VPK');

UPDATE C##ADMIN.DONVI SET TRGDV = 'TKH001' WHERE MADV = 'VPK'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV001' WHERE MADV = 'MMTVT'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV002' WHERE MADV = 'HTTT'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV003' WHERE MADV = 'CNPM'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV004' WHERE MADV = 'KHMT'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV005' WHERE MADV = 'CNTT'; 
UPDATE C##ADMIN.DONVI SET TRGDV = 'TDV006' WHERE MADV = 'TGMT'; 

INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV001', 'Nguyen Thi An', 'Nu', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '123 ABC Street, Lam Dong', '0123456789', 'CLC', 'HTTT', 24, 7.5);
INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV002', 'Tran Van Bình', 'Nam', TO_DATE('2000-02-02', 'YYYY-MM-DD'), '456 XYZ Street, Ca Mau', '0987654321', 'CLC', 'MMTVT', 21, 8.0);
INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV003', 'Pham Thi Cúc', 'Nu', TO_DATE('2000-03-03', 'YYYY-MM-DD'), '789 DEF Street, Da Nang', '0123456789', 'CQ', 'KHMT', 18, 7.2);
INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV004', 'Le Van Dung', 'Nam', TO_DATE('2000-04-04', 'YYYY-MM-DD'), '1011 GHI Street, Can Tho', '0987654321', 'CQ', 'HTTT', 27, 8.5);
INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV005', 'Nguyen Thi Hà', 'Nu', TO_DATE('2000-05-05', 'YYYY-MM-DD'), '1213 JKL Street, Dong Nai', '0123456789', 'CTTT', 'HTTT', 22, 7.8);
INSERT INTO C##ADMIN.SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, MACT, MANGANH, SOTCTL, DTBTL) VALUES ('SV006', 'Tran Van Long', 'Nam', TO_DATE('2000-06-06', 'YYYY-MM-DD'), '1415 MNO Street, Hue', '0987654321', 'VP', 'HTTT', 20, 7.0);

INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP001', 'Khai thác du lieu và ung dung', 4, 30, 15, 45, 'KHMT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP002', 'Nhap môn hoc máy', 4, 30, 15, 45, 'KHMT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP003', 'Truc quan hóa du lieu', 4, 30, 15, 45, 'HTTT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP004', 'An toan va bao mat du lieu', 4, 30, 15, 45, 'HTTT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP005', 'Nhap môn ma hoa mat ma', 4, 30, 15, 45, 'MMTVT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP006', 'Lap trinh mang', 4, 30, 15, 45, 'MMTVT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP007', 'Hoc phan A', 4, 30, 15, 45, 'VPK');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP008', 'Hoc phan B', 4, 30, 15, 45, 'VPK');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP009', 'Lap trình ung dung Java', 4, 30, 15, 45, 'CNPM');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP010', 'Phát trien ung dung web', 4, 30, 15, 45, 'CNPM');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP011', 'Xu lý anh so và video so', 4, 30, 15, 45, 'TGMT');
INSERT INTO C##ADMIN.HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, SOSVTD, MADV) VALUES ('HP012', 'Do hoa máy tính', 4, 30, 15, 45, 'TGMT');

INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP001', 1, 2024, 'CLC');
INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP002', 2, 2024, 'VP');
INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP003', 3, 2024, 'CTTT');
INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP009', 1, 2025, 'CQ');
INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP005', 2, 2025, 'CLC');
INSERT INTO C##ADMIN.KHMO (MAHP, HK, NAM, MACT) VALUES ('HP006', 3, 2025, 'VP');

INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI001', 'HP001', 1, 2024, 'CLC');
INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI002', 'HP002', 2, 2024, 'VP');
INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI003', 'HP003', 3, 2024, 'CTTT');
INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI001', 'HP009', 2, 2025, 'CQ');
INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI004', 'HP005', 2, 2025, 'CLC');
INSERT INTO C##ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT) VALUES ('GVI005', 'HP006', 3, 2025, 'VP');

INSERT INTO C##ADMIN.DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('SV001', 'GVI001', 'HP001', 1, 2024, 'CLC', 8.5, 7.0, 8.0, NULL);
INSERT INTO C##ADMIN.DANGKY (MASV, MAGV, MAHP, HK, NAM, MACT, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('SV001', 'GVI004', 'HP005', 2, 2025, 'CLC', 9.0, 8.0, NULL, NULL);

-- Tao role 
DROP ROLE RL_NHANVIENCOBAN;
DROP ROLE RL_GIANGVIEN;
DROP ROLE RL_GIAOVU;
DROP ROLE RL_TRUONGDONVI;
DROP ROLE RL_TRUONGKHOA;
DROP ROLE RL_SINHVIEN;

CREATE ROLE RL_NHANVIENCOBAN;
CREATE ROLE RL_GIANGVIEN;
CREATE ROLE RL_GIAOVU;
CREATE ROLE RL_TRUONGDONVI;
CREATE ROLE RL_TRUONGKHOA;
CREATE ROLE RL_SINHVIEN;

-- Tao user tu bang NHANSU
CREATE OR REPLACE PROCEDURE USP_CREATEUSER 
AS
    CURSOR CUR IS
        SELECT MANV
        FROM NHANSU
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS);
    STRSQL VARCHAR2(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE STRSQL;
    
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY ' || USR;
        EXECUTE IMMEDIATE STRSQL;
        
        STRSQL := 'GRANT CONNECT TO ' || USR;
        EXECUTE IMMEDIATE STRSQL;
    END LOOP;
    
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE STRSQL;
    
    CLOSE CUR;
END;
/

EXEC USP_CREATEUSER;

-- Gan role cho toan bo user trong bang NHANSU
CREATE OR REPLACE PROCEDURE USP_ADDUSERROLE
    (STRROLE VARCHAR, LOAI VARCHAR) 
AS 
    CURSOR CUR IS (SELECT MANV
        FROM NHANSU
        WHERE MANV IN (SELECT USERNAME FROM ALL_USERS) 
        AND VAITRO = LOAI); 
    STRSQL VARCHAR(2000); 
    USR VARCHAR2(50); 
BEGIN 
    OPEN CUR; 
    LOOP 
        FETCH CUR INTO USR; 
        EXIT WHEN CUR%NOTFOUND; 

        STRSQL := 'GRANT '||STRROLE||' TO '||USR; 
        EXECUTE IMMEDIATE (STRSQL); 
    END LOOP; 
    CLOSE CUR; 
END; 
/

EXEC USP_ADDUSERROLE ('RL_NHANVIENCOBAN','Nhan vien co ban');
EXEC USP_ADDUSERROLE ('RL_GIANGVIEN','Giang vien');
EXEC USP_ADDUSERROLE ('RL_GIAOVU','Giao vu');
EXEC USP_ADDUSERROLE ('RL_TRUONGDONVI','Truong don vi');
EXEC USP_ADDUSERROLE ('RL_TRUONGKHOA','Truong khoa');
/

-- Tao VPD de dung cho cac chinh sach
-- Bang DANGKY
CREATE OR REPLACE FUNCTION F_DANGKY
  (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
  USERNAME VARCHAR2(10);
  VT NVARCHAR2(50); 
  DK VARCHAR2(50);  
BEGIN
    USERNAME := SUBSTR(USER, 4);
    
    IF SUBSTR(USERNAME, 1, 3) = 'SVI' THEN
        DK := 'MASV=' || '''' || USERNAME || '''';
        RETURN DK;
    END IF;
    
    SELECT VAITRO INTO VT FROM C##ADMIN.NHANSU WHERE MANV = USERNAME;
    
    IF VT = 'Giang vien' OR VT = 'Truong don vi' THEN
        DK := 'MAGV=' || '''' || USERNAME || '''';
    ELSIF VT = 'Giao vu' OR VT = 'Truong khoa' THEN
        DK := '1=1';
    END IF;
    RETURN DK;
END F_DANGKY;
/

BEGIN
  DBMS_RLS.ADD_POLICY (
    OBJECT_SCHEMA    => 'C##ADMIN',
    OBJECT_NAME      => 'DANGKY',
    POLICY_NAME      => 'P_DANGKY',
    POLICY_FUNCTION  => 'F_DANGKY'
 );
 END;
/

-- CS#1: Nhan vien co ban 
-- Tao view xem thong tin ca nhan
CREATE OR REPLACE VIEW C##ADMIN.V_CS1_TTCANHAN
AS 
    SELECT NS.*
    FROM  NHANSU NS
    WHERE NS.MANV = SYS_CONTEXT('USERENV','SESSION_USER');
    
GRANT SELECT ON C##ADMIN.V_CS1_TTCANHAN TO RL_NHANVIENCOBAN;

-- Tao view chinh sua sdt
CREATE OR REPLACE VIEW C##ADMIN.V_CS1_SDT
AS 
    SELECT NS.DT
    FROM NHANSU NS
    WHERE NS.MANV = SYS_CONTEXT('USERENV','SESSION_USER');

GRANT UPDATE ON C##ADMIN.V_CS1_SDT TO RL_NHANVIENCOBAN;

-- Xem thong tin cac bang
GRANT SELECT ON C##ADMIN.SINHVIEN TO RL_NHANVIENCOBAN; 
GRANT SELECT ON C##ADMIN.DONVI TO RL_NHANVIENCOBAN; 
GRANT SELECT ON C##ADMIN.HOCPHAN TO RL_NHANVIENCOBAN; 
GRANT SELECT ON C##ADMIN.KHMO TO RL_NHANVIENCOBAN; 

-- Code test CS#1:
--SELECT * FROM C##ADMIN.V_CS1_TTCANHAN;

--UPDATE C##ADMIN.V_CS1_SDT
--SET DT = '0987654321';

-- CS#2: Giang vien
-- Cap quyen Nhan vien co ban
GRANT RL_NHANVIENCOBAN TO RL_GIANGVIEN;

-- Tao view xem tren bang Phan cong
CREATE OR REPLACE VIEW C##ADMIN.V_CS2_PHANCONG
AS 
    SELECT PC.*
    FROM  PHANCONG PC
    WHERE PC.MAGV = SYS_CONTEXT('USERENV','SESSION_USER');
    
GRANT SELECT ON C##ADMIN.V_CS2_PHANCONG TO RL_GIANGVIEN;

-- Cap quyen tren bang Dang ky
GRANT SELECT ON C##ADMIN.DANGKY TO RL_GIANGVIEN;
GRANT UPDATE (DIEMTH,DIEMQT,DIEMCK,DIEMTK) ON C##ADMIN.DANGKY TO RL_GIANGVIEN;

-- Tao view cap nhat diem tren bang Dang ky


-- Test CS#2
-- SELECT * FROM C##ADMIN.V_CS2_PHANCONG;

-- SELECT * FROM C##ADMIN.V_CS2_DANGKY;

-- CS#3: Giao vu
-- Cap quyen Nhan vien co ban
GRANT RL_NHANVIENCOBAN TO RL_GIAOVU;

-- Cap quyen Them va Cap nhat cho cac bang
GRANT INSERT, UPDATE ON C##ADMIN.SINHVIEN TO RL_GIAOVU;
GRANT INSERT, UPDATE ON C##ADMIN.DONVI TO RL_GIAOVU;
GRANT INSERT, UPDATE ON C##ADMIN.HOCPHAN TO RL_GIAOVU;
GRANT INSERT, UPDATE ON C##ADMIN.KHMO TO RL_GIAOVU;

-- Cap quyen xem tren bang Phan cong
GRANT SELECT ON C##ADMIN.PHANCONG TO RL_GIAOVU;

-- Tao view sua tren bang Phan cong
CREATE OR REPLACE FUNCTION C##ADMIN.F_CS3_PHANCONG
    (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2 
AS 
BEGIN 
 RETURN 'EXISTS (
    SELECT 1 
    FROM C##ADMIN.PHANCONG PC
    INNER JOIN C##ADMIN.HOCPHAN HP ON PC.MAHP = HP.MAHP
    WHERE HP.MADV = ''VPK''
  )';
END; 

BEGIN 
    dbms_rls.add_policy( 
        OBJECT_SCHEMA   =>'C##ADMIN', 
        OBJECT_NAME     =>'PHANCONG', 
        POLICY_NAME     =>'CS3_PC', 
        POLICY_FUNCTION =>'F_CS3_PHANCONG', 
        STATEMENT_TYPES =>'UPDATE', 
        UPDATE_CHECK    => TRUE 
        ); 
END;

BEGIN 
    DBMS_RLS.DROP_POLICY( 
        OBJECT_SCHEMA => 'C##ADMIN', 
        OBJECT_NAME =>'PHANCONG', 
        POLICY_NAME => 'CS3_PC'); 
END;

-- Tao view xoa hoac them tren bang Dang ky
CREATE OR REPLACE VIEW C##ADMIN.V_CS3_DANGKY
AS 
    SELECT *
    FROM DANGKY DK;
    
GRANT DELETE, INSERT ON C##ADMIN.UV_GV_DANGKI TO RL_GIAOVU;

-- CS#4: Truong don vi
-- Cap quyen Giang vien
GRANT RL_GIANGVIEN TO RL_TRUONGDONVI;

-- Tao view SELECT tren bang PHANCONG
CREATE OR REPLACE VIEW C##ADMIN.V_CS4_PHANCONG
AS 
    SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT, DV.MADV
    FROM PHANCONG PC
    JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP
    JOIN DONVI DV ON HP.MADV = DV.MADV
    WHERE DV.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON C##ADMIN.V_CS4_PHANCONG TO RL_TRUONGDONVI;

-- Tao view tren bang PHANCONG
CREATE OR REPLACE VIEW C##ADMIN.V_CS4_HOCPHAN AS
SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
FROM PHANCONG PC
JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP
JOIN DONVI DV ON HP.MADV = DV.MADV
WHERE DV.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER') AND DV.MADV = 'VPK';

GRANT INSERT, DELETE, UPDATE ON C##ADMIN.V_CS4_HOCPHAN TO RL_TRUONGDONVI;

-- CS#5: Truong khoa 
-- Cap quyen Giang vien
GRANT RL_GIANGVIEN TO RL_TRUONGKHOA;

-- Cap quyen tren bang PHANCONG
CREATE OR REPLACE VIEW C##ADMIN.V_PHANCONG_VANPHONGKHOA 
AS
    SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
    FROM PHANCONG PC
    JOIN HOCPHAN HP ON PC.MAHP = HP.MAHP
    JOIN DONVI DV ON HP.MADV = DV.MADV
    WHERE DV.TENDV = 'Van Phong Khoa';
    
GRANT INSERT, DELETE, UPDATE ON C##ADMIN.V_PHANCONG_VANPHONGKHOA TO RL_TRUONGKHOA;

-- Cap quyen tren bang NHANSU
GRANT SELECT, INSERT, DELETE, UPDATE ON C##ADMIN.NHANSU TO RL_TRUONGKHOA;

-- Cap quyen xem khong gioi han
GRANT SELECT ANY TABLE TO RL_TRUONGKHOA;

-- CS#6: Sinh vien
/
